const routes = [
    {
        path:'/',
        component:'@/pages/index.tsx',
        name:'首页',
        wrappers:[
            '@/wrappers/auth.tsx'
        ]
    },
    {
        path:'/login',
        component:'@/pages/login.tsx',
        layout:false
    },{
        path:'/error',
        component:'@/pages/error.tsx',
    },{
        path:'/test1',
        component:'@/pages/test1.tsx',
        name:'测试1',
        wrappers:[
            '@/wrappers/auth.tsx'
        ],
        routes:[
            {
                path:'/test1/test1_childOne',
                component:'@/pages/test1_childOne.tsx',
                name:'测试子页面1',
                wrappers:[
                    '@/wrappers/auth.tsx'
                ]
                // target:"_self"
            },{
                path:'/test1/test1_childTwo',
                component:'@/pages/test1_childTwo.tsx',
                name:'测试子页面2',
                wrappers:[
                    '@/wrappers/auth.tsx'
                ]
            }
        ]
    },{
        path:'/test2',
        component:'@/pages/test2.tsx',
        name:'测试2',
        wrappers:[
            '@/wrappers/auth.tsx'
        ],
        routes:[
            {
                path:'/test2/test2_childOne',
                component:'@/pages/test2_childOne.tsx',
                name:'测试子页面1',
                wrappers:[
                    '@/wrappers/auth.tsx'
                ]
            }
        ]
    },{
        path:'/test3',
        component:'@/pages/test3.tsx',
        name:'测试3',
        wrappers:[
            '@/wrappers/auth.tsx'
        ]
    },{
        path:'/dva_test',
        component:'@/pages/dva_test.tsx',
        name:'dva测试',
        wrappers:[
            '@/wrappers/auth.tsx'
        ],
        routes:[
            {
                path:'/dva_test/dva1',
                component:'@/pages/dva1',
                name:'dva1',
                wrappers:[
                    '@/wrappers/auth.tsx'
                ]
            },{
                path:'/dva_test/dva2',
                component:'@/pages/dva2',
                name:'dva2',
                wrappers:[
                    '@/wrappers/auth.tsx'
                ]
            }
        ]
    }
]

export default routes